# Current Climate Scenario
# Baseline climate conditions (already +1.51°C since 1910)

name: "current"
description: "Current climate baseline (already +1.51°C since 1910)"
display_name: "Current Climate"

# Climate effects on forest parameters
effects:
  fpi_adjustment: 1.0          # No FPI reduction
  temp_change: 0               # No additional temperature change
  rainfall_change: 0           # No rainfall change
  mortality_adjustment: 1.0    # No mortality increase
  disturbance_adjustment: 1.0  # No disturbance increase

# Climate metadata
metadata:
  temperature_baseline: "+1.51°C since 1910"
  rainfall_baseline: "Current patterns"
  fire_risk: "Current levels"
  drought_frequency: "Current patterns"
  
# Research references
references:
  - "Bureau of Meteorology (2024) State of the Climate Report"
  - "IPCC AR6 (2021) Climate Change 2021: The Physical Science Basis"
