# Paris Agreement 1.5°C Climate Scenario
# Critical threshold for forest ecosystems

name: "target15"
description: "Paris Agreement 1.5°C target - CRITICAL THRESHOLD: Forests transition from carbon sink to source during heatwaves"
display_name: "Paris 1.5°C Target"

# Climate effects on forest parameters
effects:
  fpi_adjustment: 0.88         # 12% reduction (research: 10-15% for 1.5°C)
  temp_change: 1.5             # Additional 1.5°C warming
  rainfall_change: -0.10       # 10% rainfall reduction
  mortality_adjustment: 1.15   # 15% mortality increase
  disturbance_adjustment: 1.25 # 25% disturbance increase

# Climate metadata
metadata:
  temperature_target: "1.5°C above pre-industrial"
  rainfall_change: "10% reduction"
  fire_risk: "25% increase"
  drought_frequency: "Increased"
  heatwave_intensity: "Significantly increased"
  
# Research references
references:
  - "IPCC AR6 (2021) - 1.5°C warming impacts on forests"
  - "Allen et al. (2020) - Forest mortality at 1.5°C warming"
  - "Bowman et al. (2019) - Fire risk at 1.5°C warming"
