carbon:
  price_start: 35.0
  price_growth: 0.03
  buffer: 0.20
  crediting_years: 30
  discount_rate: 0.07

costs:
  management:
    capex: 2000.0
    opex: 150.0
    mrv: 15.0
  reforestation:
    capex: 5000.0
    opex: 200.0
    mrv: 35.0
