# Light Management with Reforestation - AFM Applied to Both Standing Forest and Reforestation
# Active Forest Management applied to both existing standing forest AND reforestation sites

name: "lr"
description: "Light AFM with Reforestation - Applied to both standing forest and reforestation sites. Regular interventions with noticeable improvements and reforestation management."
display_name: "Light AFM + Reforestation"

# Management effects on forest parameters
effects:
  y_multiplier: 1.125          # 12.5% growth improvement
  mortality_factor: 0.8        # 20% mortality reduction
  disturbance_factor: 0.70     # 30% disturbance reduction (research: 62-72% fire severity reduction)
  prescribed_burn_effect: 0.09 # 9% biomass consumption from prescribed burns
  apply_to_reforestation: true # Enable management effects for reforestation scenarios

# Management practices
practices:
  prescribed_burning: "Regular (5-10 year intervals)"
  thinning: "Selective for biodiversity"
  species_mixing: "Limited"
  pest_control: "Basic"
  fire_management: "Fuel reduction"
  reforestation_management: "Basic management of reforestation areas"
  scope: "Applied to both existing standing forest AND reforestation sites"
  
# Research references
references:
  - "Fernandes & Botelho (2003) - Prescribed fire effects"
  - "Stephens et al. (2012) - Fire severity reduction (62-72%)"
  - "Lindenmayer et al. (2018) - Conservation management outcomes"
  - "Chazdon et al. (2016) - Basic managed reforestation approaches"
