#Light intensity - Adaptive Management Scenario
# Adapative management with regular with moderate severity

name: "l"
description: "Light management - Regular interventions with noticeable improvements"
display_name: "Light Management"

# Management effects on forest parameters
effects:  
  y_multiplier: 1.125          # 12.5% growth improvement
  mortality_factor: 0.8        # 20% mortality reduction
  disturbance_factor: 0.70     # 30% disturbance reduction (research: 62-72% fire severity reduction)
  prescribed_burn_effect: 0.09 # 9% biomass consumption from prescribed burns

# Management practices
practices:
  prescribed_burning: "Regular (5-10 year intervals)"
  thinning: "Selective for biodiversity"
  species_mixing: "Limited"
  pest_control: "Basic"
  fire_management: "Fuel reduction"
  
# Research references
references:
  - "Fernandes & Botelho (2003) - Prescribed fire effects"
  - "Stephens et al. (2012) - Fire severity reduction (62-72%)"
  - "Lindenmayer et al. (2018) - Conservation management outcomes"
