# Moderate Management with Reforestation - AFM Applied to Both Standing Forest and Reforestation
# Active Forest Management applied to both existing standing forest AND reforestation sites

name: "mr"
description: "Moderate AFM with Reforestation - Applied to both standing forest and reforestation sites. Moderate interventions with reforestation management."
display_name: "Moderate AFM + Reforestation"

# Management effects on forest parameters
effects:
  y_multiplier: 1.35            
  mortality_factor: 0.65       
  disturbance_factor: 0.5      
  prescribed_burn_effect: 0.15  
  apply_to_reforestation: true 

# Management practices
practices:
  prescribed_burning: "Frequent (5 year intervals)"
  thinning: "Intensive for resilience"
  species_mixing: "Climate-adapted species"
  pest_control: "Integrated pest management"
  fire_management: "Advanced fuel management"
  climate_adaptation: "Species selection for future climate"
  reforestation_management: "Active management of reforestation areas"
  scope: "Applied to both existing standing forest AND reforestation sites"
  
# Research references
references:
  - "Fernandes & Botelho (2003) - Intensive prescribed fire effects"
  - "Stephens et al. (2012) - Advanced fire management"
  - "Lindenmayer et al. (2018) - Intensive management outcomes"
  - "Prober et al. (2019) - Climate-adaptive forest management"
  - "Chazdon et al. (2016) - Managed reforestation approaches"
