# Moderate intensity - Adaptive Management Scenario
# Climate-specific adaptations with maximum improvements

name: "m"
description: "Moderate management - Climate adaptive interventions with maximum improvements"
display_name: "Moderate Management"

# Management effects on forest parameters
effects:
  y_multiplier: 1.35           # 35% growth improvement
  mortality_factor: 0.65       # 35% mortality reduction
  disturbance_factor: 0.5      # 50% disturbance reduction
  prescribed_burn_effect: 0.15 # 15% biomass consumption from frequent burns

# Management practices
practices:
  prescribed_burning: "Frequent (5 year intervals)"
  thinning: "Intensive for resilience"
  species_mixing: "Climate-adapted species"
  pest_control: "Integrated pest management"
  fire_management: "Advanced fuel management"
  climate_adaptation: "Species selection for future climate"
  
# Research references
references:
  - "Fernandes & Botelho (2003) - Frequent prescribed fire effects"
  - "Stephens et al. (2012) - Advanced fire management"
  - "Lindenmayer et al. (2018) - Adaptive management outcomes"
  - "Prober et al. (2019) - Climate-adaptive forest management"
