# Intensive intensity - Adaptive Management Scenario
# Maximum intervention with intensive forest management

name: "i"
description: "Intensive management - Maximum intervention with intensive forest management"
display_name: "Intensive Management"

# Management effects on forest parameters
effects:
  y_multiplier: 1.5            # 50% growth improvement
  mortality_factor: 0.5        # 50% mortality reduction
  disturbance_factor: 0.3      # 70% disturbance reduction
  prescribed_burn_effect: 0.2  # 20% biomass consumption from frequent burns

# Management practices
practices:
  prescribed_burning: "Very frequent (3 year intervals)"
  thinning: "Intensive for maximum growth"
  species_mixing: "Climate-adapted species with genetic diversity"
  pest_control: "Integrated pest management with monitoring"
  fire_management: "Advanced fuel management and fire breaks"
  climate_adaptation: "Species selection and assisted migration"
  carbon_monitoring: "Continuous carbon stock monitoring"
  
# Research references
references:
  - "Fernandes & Botelho (2003) - Intensive prescribed fire effects"
  - "Stephens et al. (2012) - Advanced fire management"
  - "Lindenmayer et al. (2018) - Intensive management outcomes"
  - "Prober et al. (2019) - Climate-adaptive forest management"
