# Acacia Forest & Woodland - FullCAM Calibrated Parameters
# Source: Forrester et al. (2025) Ecological Modelling 508:111204 (Table 3 means; Table 7 calibrated params).

K_AGB: 49.0
G: 10.0
root_shoot: 0.30

# NEUTRAL FPI (scenario builder will modify)
fpi_ratios:
  baseline: 1.00      # Builder will apply degradation
  management: 1.00    # Builder will apply climate
  reforestation: 1.00 # Builder will apply climate

# Initial soil carbon fractions (based on FullCAM soil organic C ~ 55.5 Mg C ha-1)
S0_deg_frac: 0.25
S0_man_frac: 0.25
S0_new_frac: 0.01

# Initial ages (used for growth calculations, not initial biomass)
age_degraded: 15
age_managed: 15
age_reforestation: 0

# FIXED INITIAL BIOMASS VALUES (tonnes/ha) - based on FullCAM typical stocks
# Above-ground biomass ~ 15.0 Mg C ha-1 = ~15.0 tonnes/ha (assuming 50% carbon content)
initial_biomass_baseline: 15.0
initial_biomass_management: 15.0
initial_biomass_reforestation: 0.0

# Mortality rates (based on FullCAM 1.825% annual mortality)
# Note: Management effects are applied by scenario builder to avoid double-counting
m_degraded: 0.022       # AFW degraded mortality (arid conditions, higher mortality)
m_managed: 0.022        # AFW managed mortality (same as degraded for now)
m_reforestation: 0.022  # AFW reforestation mortality (same as degraded for now)

# BASE disturbance (scenario builder modifies)
pdist_degraded: 0.10
pdist_managed: 0.10    # Same as degraded - builder applies reduction
pdist_reforestation: 0.10

dsev_degraded: 0.20
dsev_managed: 0.20     # Same as degraded - builder applies reduction
dsev_reforestation: 0.20

# NEUTRAL TYF calibrations (builder applies management effects)
# NEUTRAL TYF
tyf_calibrations:
  baseline:
    M: 49.0
    G: 10.0
    y: 1.0        # Builder applies management
  management:
    M: 49.0
    G: 10
    y: 1.0        # Builder applies management
  reforestation:
    M: 49.0
    G: 10.0
    y: 1.0        # Builder applies management

# FullCAM-derived parameters (for reference and future model enhancement)
fullcam_parameters:

  tyf_G: 10.0
  frFracInit: 0.63

  # Standing dead -> debris turnover
  bkdnFracSDdwdF: 3
  atmsFracSDdwdBkdnF: 0.221
  bkdnFracSChwdF: 3
  atmsFracSChwdBkdnF: 0.31  

  # Standing bark & leaves turnover
  bkdnFracSBlitF: 2
  atmsFracSBlitBkdnF: 0.853
  bkdnFracSLlitF: 2
  atmsFracSLlitBkdnF: 0.714

  # Roots & soil pathways
  bkdnFracRCodrF: 2.478
  rFracFirtF: 0.709
  
  # Respiration fractions (debris -> soil)
  atmsFracRDdwdBkdnF: 0.694
  atmsFracRBlitBkdnF: 0.815
  atmsFracDLlitBkdnF: 0.768
  atmsFracRLlitBkdnF: 0.609
  atmsFracRCodrBkdnF: 0.659

  # Typical AFW carbon stocks
typical_carbon_stocks:
  above_ground_biomass: 25
  standing_dead: 0.8
  coarse_woody_debris: 4.0
  total_woody_debris: 4.4
  bark_debris: 0.2
  foliage_debris: 0.9
  soil_organic_carbon: 31.9
