# Custom Forest Type - Test Configuration
# This demonstrates how to add custom forest types

# Forest type parameters
K_AGB: 200.0  # Maximum potential biomass (tonnes/ha)
G: 12.0       # Age of maximum growth rate
root_shoot: 0.30  # Root-to-shoot ratio

# NEUTRAL FPI (scenario builder will modify)
fpi_ratios:
  baseline: 1.00      # Builder will apply degradation
  management: 1.00    # Builder will apply climate
  reforestation: 1.00 # Builder will apply climate

# Initial soil carbon fractions
S0_deg_frac: 0.15   # Initial soil carbon for custom forest
S0_man_frac: 0.15   # Same for management
S0_new_frac: 0.02   # Reforestation starts with minimal soil carbon

# Initial ages (used for growth calculations, not initial biomass)
age_degraded: 10
age_managed: 10
age_reforestation: 0

# FIXED INITIAL BIOMASS VALUES (tonnes/ha)
initial_biomass_baseline: 50.0     # Custom forest AGB
initial_biomass_management: 50.0   # Same starting biomass for management
initial_biomass_reforestation: 0.0 # Reforestation starts from zero

# Mortality rates (based on FullCAM 1.825% annual mortality)
# Note: Management effects are applied by scenario builder to avoid double-counting
m_baseline: 0.020       # Custom forest baseline mortality

# BASE disturbance (scenario builder modifies)
pdist_degraded: 0.12
pdist_managed: 0.12    # Same as degraded - builder applies reduction
pdist_reforestation: 0.12

dsev_degraded: 0.25
dsev_managed: 0.25     # Same as degraded - builder applies reduction
dsev_reforestation: 0.25

# NEUTRAL TYF calibrations (builder applies management effects)
# NEUTRAL TYF
tyf_calibrations:
  baseline:
    M: 200.0      # Maximum potential biomass
    G: 12.0       # Age of maximum growth rate
    y: 1.0        # Neutral growth multiplier (builder applies degradation)
    c: 0.47       # Carbon fraction of biomass
    k: 0.5        # Shape parameter
    a: 0.0        # Age offset
    b: 1.0        # Growth rate scaling
  
  management:
    M: 200.0      # Same maximum potential biomass
    G: 12.0       # Same age of maximum growth rate
    y: 1.0        # Neutral growth multiplier (builder applies management)
    c: 0.47       # Carbon fraction of biomass
    k: 0.5        # Shape parameter
    a: 0.0        # Age offset
    b: 1.0        # Growth rate scaling
  
  reforestation:
    M: 200.0      # Same maximum potential biomass
    G: 12.0       # Same age of maximum growth rate
    y: 1.0        # Neutral growth multiplier (natural reforestation)
    c: 0.47       # Carbon fraction of biomass
    k: 0.5        # Shape parameter
    a: 0.0        # Age offset
    b: 1.0        # Growth rate scaling

# Economic parameters (optional - can be overridden by management configs)
economics:
  carbon:
    price_start: 50.0
    price_growth: 0.02
    buffer: 0.05
    crediting_years: 25
    discount_rate: 0.05
  costs:
    baseline:
      capex: 0.0
      opex: 0.0
      mrv: 0.0
    management:
      capex: 1000.0
      opex: 50.0
      mrv: 25.0
    reforestation:
      capex: 2000.0
      opex: 50.0
      mrv: 25.0
